// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZoL2G1AZzM8EpZMu9GQfEusNwP8Wt66E',
    appId: '1:912547198814:web:ce7f9ff488826675ee81cf',
    messagingSenderId: '912547198814',
    projectId: 'fakestore-d8ae2',
    authDomain: 'fakestore-d8ae2.firebaseapp.com',
    storageBucket: 'fakestore-d8ae2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw0GCPj0zUBnSay8zMRoAOHzlf5z06yLo',
    appId: '1:912547198814:android:376d574bb4ad53dcee81cf',
    messagingSenderId: '912547198814',
    projectId: 'fakestore-d8ae2',
    storageBucket: 'fakestore-d8ae2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJwvfKlApigwnqs9Tn_wOxJF8o-W51AKU',
    appId: '1:912547198814:ios:8c2bbb5f25b23fd7ee81cf',
    messagingSenderId: '912547198814',
    projectId: 'fakestore-d8ae2',
    storageBucket: 'fakestore-d8ae2.appspot.com',
    iosBundleId: 'com.example.fakestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJwvfKlApigwnqs9Tn_wOxJF8o-W51AKU',
    appId: '1:912547198814:ios:8c2bbb5f25b23fd7ee81cf',
    messagingSenderId: '912547198814',
    projectId: 'fakestore-d8ae2',
    storageBucket: 'fakestore-d8ae2.appspot.com',
    iosBundleId: 'com.example.fakestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZoL2G1AZzM8EpZMu9GQfEusNwP8Wt66E',
    appId: '1:912547198814:web:07fb815148ccce80ee81cf',
    messagingSenderId: '912547198814',
    projectId: 'fakestore-d8ae2',
    authDomain: 'fakestore-d8ae2.firebaseapp.com',
    storageBucket: 'fakestore-d8ae2.appspot.com',
  );
}
